/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.99
 * Generated at: 2025-03-25 15:12:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import org.example.Model.Tache;
import java.text.SimpleDateFormat;

public final class task_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("org.example.Model.Tache");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Liste des Tâches</title>\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-100 text-gray-900\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container mx-auto p-6\">\r\n");
      out.write("        <header class=\"mb-8\">\r\n");
      out.write("            <h1 class=\"text-3xl font-semibold text-center text-gray-800 mb-4\">Gestion des Tâches</h1>\r\n");
      out.write("            <nav class=\"text-center\">\r\n");
      out.write("                <ul class=\"flex justify-center space-x-6\">\r\n");
      out.write("                    <li><a href=\"index.jsp\" class=\"text-blue-600 hover:text-blue-800\">Accueil</a></li>\r\n");
      out.write("                    <li><a href=\"ProjetServlet\" class=\"text-blue-600 hover:text-blue-800\">Projets</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <h2 class=\"text-3xl font-semibold text-center text-gray-800 mb-6\">Liste des Tâches</h2>\r\n");
      out.write("\r\n");
      out.write("        <table class=\"min-w-full bg-white border border-gray-300 rounded-lg shadow-lg\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr class=\"bg-blue-600 text-white\">\r\n");
      out.write("                    <th class=\"py-2 px-4 border-b\">Description</th>\r\n");
      out.write("                    <th class=\"py-2 px-4 border-b\">Date de Début</th>\r\n");
      out.write("                    <th class=\"py-2 px-4 border-b\">Date de Fin</th>\r\n");
      out.write("                    <th class=\"py-2 px-4 border-b\">Ressources</th>\r\n");
      out.write("                    <th class=\"py-2 px-4 border-b\">Actions</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                ");

                    // Retrieve the list of tasks from the request attribute
                    List<Tache> taches = (List<Tache>) request.getAttribute("taches");

                    // If the list is null, initialize an empty list
                    if (taches == null) {
                        taches = new java.util.ArrayList<>();
                    }

                    // Iterate over each task and display it in the table
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    for (Tache tache : taches) {
                
      out.write("\r\n");
      out.write("                <tr class=\"hover:bg-gray-100\">\r\n");
      out.write("                    <td class=\"py-2 px-4 border-b\">");
      out.print( tache.getDescription() );
      out.write("</td>\r\n");
      out.write("                    <td class=\"py-2 px-4 border-b\">\r\n");
      out.write("                        ");
      out.print( (tache.getDateDebutTache() != null) ? sdf.format(tache.getDateDebutTache()) : "" );
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"py-2 px-4 border-b\">\r\n");
      out.write("                        ");
      out.print( (tache.getDateFinTache() != null) ? sdf.format(tache.getDateFinTache()) : "" );
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"py-2 px-4 border-b\">");
      out.print( tache.getRessource() );
      out.write("</td>\r\n");
      out.write("                    <td class=\"py-2 px-4 border-b\">\r\n");
      out.write("                        <a href=\"TacheServlet?action=delete&id=");
      out.print( tache.getId_tache() );
      out.write("&id_projet=");
      out.print( request.getAttribute("id_projet") );
      out.write("\" class=\"text-red-500 hover:text-red-700\">Supprimer</a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("        <h3 class=\"text-2xl font-semibold mt-8 mb-4\">Ajouter une Nouvelle Tâche</h3>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"TacheServlet\" method=\"POST\" class=\"bg-white p-6 rounded-lg shadow-md\">\r\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"add\">\r\n");
      out.write("            <input type=\"hidden\" name=\"id_projet\" value=\"");
      out.print( request.getAttribute("id_projet") );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <label for=\"id_tache\" class=\"block text-gray-700 font-medium\">Tâche Id :</label>\r\n");
      out.write("                <input type=\"number\" id=\"id_tache\" name=\"id_tache\" class=\"w-full px-4 py-2 border border-gray-300 rounded-md\" required><br><br>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <label for=\"description\" class=\"block text-gray-700 font-medium\">Description :</label>\r\n");
      out.write("                <input type=\"text\" id=\"description\" name=\"description\" class=\"w-full px-4 py-2 border border-gray-300 rounded-md\" required><br><br>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <label for=\"start_date\" class=\"block text-gray-700 font-medium\">Date de Début :</label>\r\n");
      out.write("                <input type=\"date\" id=\"start_date\" name=\"start_date\" class=\"w-full px-4 py-2 border border-gray-300 rounded-md\"><br><br>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <label for=\"end_date\" class=\"block text-gray-700 font-medium\">Date de Fin :</label>\r\n");
      out.write("                <input type=\"date\" id=\"end_date\" name=\"end_date\" class=\"w-full px-4 py-2 border border-gray-300 rounded-md\"><br><br>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <label for=\"ressource\" class=\"block text-gray-700 font-medium\">Ressources :</label>\r\n");
      out.write("                <input type=\"text\" id=\"ressource\" name=\"ressource\" class=\"w-full px-4 py-2 border border-gray-300 rounded-md\"><br><br>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\" class=\"bg-blue-600 text-white px-4 py-2 rounded-md\">Ajouter Tâche</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
